### ISSUE TITLE
LaraParse subclasses and Form::model()

### ISSUE THREAD

**Issue by eddnav** [HipsterJazzbo/LaraParse#10]
Is there a way for Form::model() to use LaraParse's subclasses as models?

My classes are using  use CastsParseProperties; so the fields can be accessed as properties, but Form::model doesn't detect this (the data is there, I've checked).

**Comment by hipsterjazzbo** [comment]
I don't think that can be a supported use case. The Form builder is not only bundled in the main framework anymore, but also pretty tightly tied into using Eloquent I think.
