### ISSUE TITLE
getCurrentUser null

### ISSUE THREAD

**Issue by eddnav** [HipsterJazzbo/LaraParse#11]
Is there a reason ParseUser::getCurrentUser returns null? according to this: http://stackoverflow.com/questions/25347123/new-parse-com-php-api-currentuser-not-giving-back-a-user, a session storage must be initialized. I looked in the source code and it doesn't seem to be used at first glance.

**Comment by nicklee1990** [comment]
Just use Auth::user() as you would with the usual Laravel set up. Then you get properties as follows:
Auth::user()->email

You can also use the Auth methods e.g Auth::id()

**Comment by eddnav** [comment]
What about Parse's session tokens?

**Comment by nicklee1990** [comment]
To be honest I've not had a use for the Parse Session so I've never looked though I can see some sessions being created in my Parse Data Browser.

I'll have a look tonight and see what can be done. What's the use case you're trying to achieve?

**Comment by nicklee1990** [comment]
@HipsterJazzbo any thoughts?

**Comment by hipsterjazzbo** [comment]
I've just run into this same issue. I'll have to dig into it, don't really have any idea ATM.

**Comment by nicklee1990** [comment]
What would this enable? The user not having to log in when revisiting the site? Could you just create a parse session driver?

**Comment by hipsterjazzbo** [comment]
@nicklee1990 That might be the way to go. I'll have a look into that.

**Comment by eddnav** [comment]
@nicklee1990 Initially, I was trying to set up an integration between Parse's PHP and JS SDK so I wouldn't have to upload some files to my server, instead directly to Parse.

@HipsterJazzbo What about ACLs? if the current parse user isn't set, I believe it won't be visible for access lists, I'm having this issue at the moment I think. I have an object with a read/write ACL set to an user and it doesn't seem to be visible.

**Comment by nicklee1990** [comment]
just having a look at this https://www.parse.com/docs/php/guide#users-session-storage-interface - perhaps this would be the way forward (and the help item above it)?

**Comment by nicklee1990** [comment]
will commit a fix for this later today once I tidy it up
