### ISSUE TITLE
php artisan vendor:publish -- Nothing to publish.

### ISSUE THREAD

**Issue by ghost** [HipsterJazzbo/LaraParse#13]
Hey guys.. wanted to let you know that following the directions in the readme, when I get to the point where I do the command:

php artisan vendor:publish --provider=hipsterjazzbo/laraparse

composer responds with:
Nothing to publish.

And no configuration file is copied into app/config.

**Comment by hipsterjazzbo** [comment]
Hmm not sure about that one. Will have to investigate.

**Comment by iamraffe** [comment]
That happened to me too, had to run 
php artisan vendor:publish
or just copy the file.

**Comment by nicklee1990** [comment]
looks like the docs need to be updated to specify the config tag i.e. php artisan vendor:publish --provider=hipsterjazzbo/laraparse --tag=config

**Comment by nicklee1990** [comment]
updated the readme for this
