### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by iamraffe** [HipsterJazzbo/LaraParse#24]
This is what I am getting while trying to install on 5.1.

---

Using version ^0.0.8 for hipsterjazzbo/laraparse
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for hipsterjazzbo/laraparse ^0.0.8 -> satisfiable by hipsterjazzbo/laraparse[v0.0.8].
    - hipsterjazzbo/laraparse v0.0.8 requires laravel/framework 5.0.\* -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

---

Anyone successfully installed on 5.1?

**Comment by nicklee1990** [comment]
yeah I'm up and running on 5.1. Looking at the composer for the repo it looks fine:
"laravel/framework": "5.0._|5.1._",

Can you paste your composer json?

my composer json has "laravel/framework": "5.*" I think from memory, will check later

**Comment by iamraffe** [comment]
My composer has "laravel/framework": "5.1.*"

This is the composer after a fresh install (with laravel new command)

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1._"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9._",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

After the fresh install I tried install LaraParse and that's when I got that error.

**Comment by nicklee1990** [comment]
Probably because we hadn't released the latest commits which updated to 5.1. v0.0.9 should fix this which i've done now - run composer update to get the latest. Let me know

**Comment by iamraffe** [comment]
My composer refuses to acknowledge the existence of version 0.0.9, insists on 0.0.8. 

Will try again later.

**Comment by nicklee1990** [comment]
yeah mine was but its just updated now
