### ISSUE TITLE
Bug with DateTime/Carbon

### ISSUE THREAD

**Issue by eddnav** [HipsterJazzbo/LaraParse#26]
I'm doing something like this

``` php
$user = $this->auth->user();
$obj = ...

$user->someDate = $obj->getCreatedAt();
$user->save();

```

It throws the following error:

```
Argument 1 passed to App\ParseClasses\History::createCarbonFromDateTime() must be an instance of LaraParse\Traits\DateTime, instance of DateTime given, called in .../vendor/hipsterjazzbo/laraparse/src/Traits/CastsParseProperties.php on line 65 and defined
```

I fixed this by importing the correct DateTime and Carbon classes in your Traits class, if this is indeed a bug I can publish a pull request for it.

In case I'm misunderstanding something, orientation would be very appreciated.

**Comment by nicklee1990** [comment]
I haven't seen this myself though I don't believe I've tried to do what you're trying. Can you create a PR and I'll have a look tonight and merge once I verify?

**Comment by eddnav** [comment]
I cloned your repo and it does have the proper includes (use Carbon\Carbon;
use DateTime;), it seems the issue was on my copy of LaraParse for some reason..., I'll be closing this now.
