### ISSUE TITLE
Unable to publish assets

### ISSUE THREAD

**Issue by oflannabhra** [HipsterJazzbo/LaraParse#27]
Laravel 5.1, Laraparse is only required package.
`php artisan vendor:publish --provider=hipsterjazzbo/laraparse --tag=config` command results in `Nothing to publish.`. Manually adding `parse.php` to `app/config` worked fine, but I figured I'd create this issue in case someone else ran into trouble

**Comment by iamraffe** [comment]
Yes, I too had issues. Had to run php artisan vendor:publish instead.

**Comment by nicklee1990** [comment]
yeah i'm seeing the issue but looking at the service provider code cannot see why its not working...

**Comment by nicklee1990** [comment]
actually i see what was wrong. Needs to be:
php artisan vendor:publish  --provider="LaraParse\ParseServiceProvider" --tag="config"
