### ISSUE TITLE
Subclass generator does not fill in class name

### ISSUE THREAD

**Issue by oflannabhra** [HipsterJazzbo/LaraParse#28]
Running `php artisan parse:subclass ClassName` generates `ClassName.php` in `app/ParseClasses/`, but does populate fields properly. I'm attaching the generated file, but will look into the cause as well.

``` php
<?php

namespace {{namespace}};

use Parse\ParseObject;
use LaraParse\Traits\CastsParseProperties;

/**
 * Class {{class}}
 *
 * @package LaraParse
 */
class {{class}} extends ParseObject
{
    use CastsParseProperties;

    public static $parseClassName = 'ClassName';
}
```

**Comment by nicklee1990** [comment]
think this was spotted in issue #25. I'll fix and release tonight
