### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mnek84** [HipsterJazzbo/LaraParse#31]
Hi! once i execute this code if (Auth::attempt(['username' => $username, 'password' => $password],$remember)) i get the user logged (and also the parse _session class return me the session key), but i can't get information about the user if a navigate to another page. (There is something related to session or Auth)

**Comment by nicklee1990** [comment]
What code are you using to try and get user info and what error message do you see?

**Comment by mnek84** [comment]
I Try Auth::User(), $user = \App\ParseClasses\User::getCurrentUser();, and all of this return null

**Comment by nicklee1990** [comment]
can you paste the function where you are logging the user in?

**Comment by mnek84** [comment]
```
if (Auth::attempt(['username' => $username, 'password' => $password],$remember))
{
    /*$user = User::logIn($username,$password);
    $user = ParseUser::getCurrentUser();
    $user->save();*/



    dd("logged in");
}else{
    dd("not logged int");
}
```

**Comment by mnek84** [comment]
I finally resolve the issue here, was related to the dd function was breaking up the session.. i don't know why!

**Comment by nicklee1990** [comment]
Here's why: http://stackoverflow.com/questions/23917409/laravel-session-data-not-sticking-across-page-loads
