### ISSUE TITLE
New user registration not working (similar to #36 and #37)

### ISSUE THREAD

**Issue by uveski** [HipsterJazzbo/LaraParse#38]
Hi,   appreciate any help while I also try to solve.

Similar to #36 and #37 - I can login but cannot register a new user.  Both #36 #37 are closed with "got it working" so any chance someone can post the actual solution / insight that we all seem to be missing?   

Registration seems to still point at mySQL in order to first validate the new user email as unique within Illuminate/Database/Connection.php and so not using the Parse driver.

PDOException in Connection.php line 310:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myapp.users' doesn't exist
1.  My auth.php
   'driver' => 'parse',
   'model' => LaraParse\Subclasses\User::class,
2.  My AuthController.php matches that posted in #36.
3.   Does config/auth.php 'table' => 'users'  need to change to 'table' => 'user'  ?
4.  No changes made to config/database.php

Greatly appreciate any insight.

**Comment by ChumburidzeGio** [comment]
+1

**Comment by dmarcos89** [comment]
@uveski  could you resolve it? id appreciate your help! (im new to laravel).
i did the same as you, but couldn't make it work yet!
regards

**Comment by digitalturtle** [comment]
Here is a sample auth controller which works. Note I'm using a custom User class and Registrar class, if you aren't you'd need to import the LaraParse stuff

    <?php namespace App\Http\Controllers\Auth;
    
    use App\Http\Controllers\Controller;
    use App\ParseClasses\User;
    use App\Services\Registrar;
    use Illuminate\Contracts\Auth\Guard;
    use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
    use Illuminate\Http\Request;
    use Illuminate\Support\Collection;
    use Parse\ParseClient;
    use Parse\ParseException;
    use Session;
    
    /**
     * Class AuthController
     * @package App\Http\Controllers\Auth
     */
    class AuthController extends Controller
    {
        use AuthenticatesAndRegistersUsers;
    
        public $redirectPath = '/user';

        public function __construct(Guard $auth, Registrar $registrar, User $user)
        {
            $this->auth = $auth;
            $this->registrar = $registrar;
            $this->user = $user;    
            $this->middleware('guest', ['except' => 'getLogout']);
        }
   
        /**
         * Handle a login request to the application.
         *
         * @param  \Illuminate\Http\Request $request
         * @return \Illuminate\Http\Response
         */
        public function postLogin(Request $request)
        {
            $this->validate($request, [
                'email' => 'required|email',
                'password' => 'required',
            ]);
    
            $credentials = $request->only('email', 'password');
    
            if ($this->auth->attempt($credentials, $request->has('remember_token'))) {
                return redirect()->intended($this->redirectPath());
            }
    
            return redirect($this->loginPath())
                ->withInput($request->only('email', 'remember_token'))
                ->withErrors([
                    'email' => $this->getFailedLoginMessage(),
                ]);
        }
    
        /**
         * @param Request $request
         * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
         */
        public function postRegister(Request $request)
        {
            $validator = $this->registrar->validator($request->all());
    
            if ($validator->fails()) {
                $this->throwValidationException(
                    $request, $validator
                );
            }
    
            $this->auth->login($this->registrar->create($request->all()));
    
            return redirect()->intended($this->redirectPath());
        }
    }

**Comment by nicklee1990** [comment]
Here is a sample auth controller which works. Note I'm using a custom User class and Registrar class, if you aren't you'd need to import the LaraParse stuff

```
<?php namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\ParseClasses\User;
use App\Services\Registrar;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Parse\ParseClient;
use Parse\ParseException;
use Session;

/**
 * Class AuthController
 * @package App\Http\Controllers\Auth
 */
class AuthController extends Controller
{
    use AuthenticatesAndRegistersUsers;

    public $redirectPath = '/user';

    public function __construct(Guard $auth, Registrar $registrar, User $user)
    {
        $this->auth = $auth;
        $this->registrar = $registrar;
        $this->user = $user;    
        $this->middleware('guest', ['except' => 'getLogout']);
    }

    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function postLogin(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
            'password' => 'required',
        ]);

        $credentials = $request->only('email', 'password');

        if ($this->auth->attempt($credentials, $request->has('remember_token'))) {
            return redirect()->intended($this->redirectPath());
        }

        return redirect($this->loginPath())
            ->withInput($request->only('email', 'remember_token'))
            ->withErrors([
                'email' => $this->getFailedLoginMessage(),
            ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function postRegister(Request $request)
    {
        $validator = $this->registrar->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $this->auth->login($this->registrar->create($request->all()));

        return redirect()->intended($this->redirectPath());
    }
}
```

**Comment by dmarcos89** [comment]
Thanks man, but it is still not working.
Im really sorry to bother you, im new on laravel.

so after using your controller, and changing the parts of the User and Registrar:

```
<?php namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
// use App\ParseClasses\User;
// use App\Services\Registrar;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Parse\ParseClient;
use Parse\ParseException;
use Session;



/**
 * Class AuthController
 * @package App\Http\Controllers\Auth
 */
class AuthController extends Controller
{
    use AuthenticatesAndRegistersUsers;

    public $redirectPath = '/user';

    public function __construct(Guard $auth, \Laraparse\Auth\Registrar $registrar, \Laraparse\Subclasss\User $user)
    {
        $this->auth = $auth;
        $this->registrar = $registrar;
        $this->user = $user;    
        $this->middleware('guest', ['except' => 'getLogout']);
    }

    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function postLogin(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email',
            'password' => 'required',
        ]);

        $credentials = $request->only('email', 'password');

        if ($this->auth->attempt($credentials, $request->has('remember_token'))) {
            return redirect()->intended($this->redirectPath());
        }

        return redirect($this->loginPath())
            ->withInput($request->only('email', 'remember_token'))
            ->withErrors([
                'email' => $this->getFailedLoginMessage(),
            ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function postRegister(Request $request)
    {
        $validator = $this->registrar->validator($request->all());

        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        }

        $this->auth->login($this->registrar->create($request->all()));

        return redirect()->intended($this->redirectPath());
    }
}
```

ReflectionException in Container.php line 795:
Class Laraparse\Auth\Registrar does not exist

I know im missing something stupid like a 'Use ....'
Thanks again!

**Comment by nicklee1990** [comment]
You should just put the following where your imports/aliases are (in places of my custom ones) 

```
use LaraParse\Auth\Registrar
use LaraParse\Subclasses\User
```

**Comment by dmarcos89** [comment]
Im not sure whats going on. I have changed what you told me, but it is not working.

I can see the blade templates fine, but when trying to register or login, nothing happens. Login error messages, or if left the fields empty nothing happens. 

Which is the best way to debug this? Thanks again man!

**Comment by nicklee1990** [comment]
check your laravel log and see what it says

**Comment by nicklee1990** [comment]
@dmarcos89 did you resolve this?

**Comment by dmarcos89** [comment]
Yes, thanks man!!!

**Comment by nicklee1990** [comment]
no probs!
