### ISSUE TITLE
auth/login not work 

### ISSUE THREAD

**Issue by backersh** [HipsterJazzbo/LaraParse#39]
Hello Dear 
@victorgram
@nicklee1990
@HipsterJazzbo
I followed your instructions that you mentioned here , am also working with laraParse provider .
I am trying to login with exist users on my parse User table but the login failed and I am getting this message

These credentials do not match our records.

Note : registration work fine

thanks

**Comment by nicklee1990** [comment]
That is just the standard parse invalid login details. Check your form to ensure you are passing the login credentials correctly

**Comment by backersh** [comment]
@nicklee1990  
I check the form the posted data look like this I think there is nothing wrong with these data sent !!

credentials array
array(2) { ["email"]=> string(20) "backersh@hotmail.com" ["password"]=> string(8) "password" }

these credentials are exist in the User table

**Comment by nicklee1990** [comment]
Hmm perhaps because the field name is "email" rather than "username" it is not using the correct details

**Comment by backersh** [comment]
I checked this also , same issue , Its weird how registration works correctly but login not .
when I register new user  the user is authenticated correctly but using login is not .
I am using this AuthController that you mentioned in  #36 post

**Comment by backersh** [comment]
@nicklee1990 

this is link of the AuthController 

https://drive.google.com/file/d/0BzgxVoERZTStZmItNmlsOHFBRnM/view?usp=sharing

**Comment by backersh** [comment]
@nicklee1990  

this is a link of the AuthController 

https://drive.google.com/file/d/0BzgxVoERZTStZmItNmlsOHFBRnM/view?usp=sharing

**Comment by backersh** [comment]
@nicklee1990 
this is a link of the AuthController , auth.php , User.php

https://drive.google.com/file/d/0BzgxVoERZTStUm9TU2o5VXJYdUU/view?usp=sharing

**Comment by nicklee1990** [comment]
i think you'll need to do some more debugging before i can help you with this one. try logging the response from Parse and adding logging at various points of the login process. as i said, the error message suggests it's a case of wrong auth details

**Comment by backersh** [comment]
Hello @nicklee1990 

I did some debugging again and I changed the email by username, authentication succeed  and redirected to home view but auth not working , I want to retrieve the authenticated user id and name  but this error appeared  Trying to get property of non-object , and I noticed that also I can return to the login view which is not correct to happen .

**Comment by backersh** [comment]
I found the solution 
thanks for help :)

**Comment by dmarcos89** [comment]
hi @nicklee1990 , could help me installing this?

Could you provide me sample codes for User.php class and AuthController.php? 
I have already set config driver to 'Parse' and set the Keys, but im new to Laravel and don't know how to procceed!!!

Regards!!
