### ISSUE TITLE
Integrate Only Auth Provider

### ISSUE THREAD

**Issue by chlebta** [HipsterJazzbo/LaraParse#4]
Hello, Please How to integrate the Auth part only

**Comment by nicklee1990** [comment]
What's the issue you're having? Did you follow the docs? 

Install the package via composer, publish the Parse config then put your keys in and change the auth driver to 'parse'. Then the authentication will work fine. You're free to continue using the Parse SDK as you would use it without having installed this package e.g. 

$query = new ParseQuery("MyClass");
$results = $query->find();

You might have to put the following in your controller:

use Parse\ParseObject;
use Parse\ParseQuery;
use Parse\ParseException;

**Comment by hipsterjazzbo** [comment]
There isn't a way to separate just one part of this package, however if you only want to use the Auth part, just change your auth driver in `config/auth.php` to `'parse'` and don't use the rest of the features :)
