### ISSUE TITLE
Master Key for User Authentication

### ISSUE THREAD

**Issue by StuStirling** [HipsterJazzbo/LaraParse#40]
Why do we need to provide the master key for user authentication? I don't want to include the master key in my application

**Comment by digitalturtle** [comment]
which bit of code are you referring to?

**Comment by nicklee1990** [comment]
which bit of code are you referring to? you don't have to use the master key, it's set to false by default in the Abstract Repo. Just put the master key in your .env file, or just put some dummy string in there

**Comment by StuStirling** [comment]
If I don't put my Master key into the .env file it won't allow me to login. Are you saying that if I just put a dummy string in it will work?

**Comment by nicklee1990** [comment]
i've never tested it but i think it should. Why are you against putting your Master Key in your .env file? It's not really any different to putting your db credentials in there.

It's not actually LaraParse that is mandating the presence of your master key, its the underlying ParseClient (which is used by LaraParse) which is part of the Parse PHP SDK. I

https://github.com/ParsePlatform/parse-php-sdk/blob/master/src/Parse/ParseClient.php

I quickly had a look through the ParseClient file I've linked to and it defaults $useMasterKey to false so if you just put in a dummy string it should work:

```
 if ($useMasterKey) {
    $headers[] = 'X-Parse-Master-Key: '.self::$masterKey;
 }
```

Haven't had a proper look so not sure but there's only one way to find out!
