### ISSUE TITLE
Which is the best email verification and recover password functionalities approach?

### ISSUE THREAD

**Issue by dmarcos89** [HipsterJazzbo/LaraParse#44]
Hi guys, i just want you to ask and learn which is the best way to develop email-verification and password recovery when using laravel and parse.com platform.

From what i read (and test), parse provides a built-in email verification working very nice, but if some customization is needed (eg: email verification needs to be used in 12hs), it becomes useless.

From the other side, the emailVerified column is not editable or cant be seted by code, so another approach needs another new column, which doesn't seems right...

What do you guys think? Probably you faced the same problem.
Hope im clear, and thanks again for your great repo! it works like a charm,

regards!!

**Comment by nicklee1990** [comment]
I've never actually needed to use anything but the standard parse password reset and email verification with custom email templates.

For email verification you can always just turn off Parse email verification, then add some columns like emailVerificationExpiry and xEmailVerified them handle it all yourself  server side including emails. 

Maybe you could do something with Parse Frame but I'm not a pro customer so I'm not sure!
