### ISSUE TITLE
Allow Laravel 5.2

### ISSUE THREAD

**Issue by tatocaster** [HipsterJazzbo/LaraParse#45]
Please update repository to allow Laravel 5.2 in composer.

**Comment by hipsterjazzbo** [comment]
I was going to do that today but now it sort of doesn't seem worth it: http://blog.parse.com/announcements/moving-on/

**Comment by tatocaster** [comment]
Damn it! Why ? :/ too bad.

**Comment by eddnav** [comment]
http://blog.parse.com/announcements/introducing-parse-server-and-the-database-migration-tool/, it might still be worth it.

**Comment by tatocaster** [comment]
Yeah, i tried it on Heroku. Its awesome

**Comment by gweiss27** [comment]
Can you please update this so we can migrate up to Laravel 5.2.  Would really appreciate it!  Thanks so much!!!!!

**Comment by shalomabitan** [comment]
Yes! can you please update

**Comment by nicklee1990** [comment]
pull request merged which allows it. let me know of any issues
