### ISSUE TITLE
User subclass requires update for Laravel 5.2

### ISSUE THREAD

**Issue by gweiss27** [HipsterJazzbo/LaraParse#46]
Hey all,

The User subclass needs a small update to work for Laravel 5.2.  The auth contract requires implementing the following function:

```
public function getAuthIdentifierName()
{
    return $this->getAuthIdentifierName();
}
```

Everything else seems to work once this is completed.  I can try to do this but I've never done a merge request.

Can anyone help?

Thanks!

Greg

**Comment by gweiss27** [comment]
I created a merge request for this.  Can someone approve it?

Thanks!

**Comment by nicklee1990** [comment]
just released fix for this issue
