### ISSUE TITLE
Laravel 5.3 support?

### ISSUE THREAD

**Issue by SamuelNCarvalho** [HipsterJazzbo/LaraParse#52]
Support for laravel 5.3 will be released when?

**Comment by nicklee1990** [comment]
PRs welcome. There are several changes which need to be made when someone has time to support self hosted Parse instances

El 20 sept 2016, a las 12:52, Samuel Carvalho <notifications@github.com<mailto:notifications@github.com>> escribi?:

Support for laravel 5.3 will be released when?

##
