### ISSUE TITLE
Recommended of setting custom registration fields

### ISSUE THREAD

**Issue by ghost** [HipsterJazzbo/LaraParse#7]
I want to add some custom registration fields. 

I can replace the default generated App/Services/Registrar with LaraParse/Auth/Registrar and then change the create() method to do what I want. 

Is this the best way to do this, or is there a better way?

**Comment by nicklee1990** [comment]
The best way in my view would be to simply change the the App/Services/Registrar to extend LaraParse/Auth/Registrar then override the create method.

**Comment by ghost** [comment]
Thanks. Overriding create worked. Using the validator is a bit quirky since it is declared private in the parent class. However I just copied the way the constructor was being called and it works.

Thanks!
