### ISSUE TITLE
Unable to use query when adding methods to Parse Repository

### ISSUE THREAD

**Issue by nicklee1990** [HipsterJazzbo/LaraParse#8]
I'm unable to add some additional methods to my Parse repositories because the $query and $useMasterKey variables are defined as having private access. I'm trying to add the following method:
public function afterDate($date){
        $this->query->equalTo('createdAt',$date);
        return $this->query->find($this->useMasterKey);
    }

to enable me to filter parse results by date. However I can't use $this->query since $query has private access. I'm thinking $query and $useMasterKey should be protected rather than private in the AbstractParseRepository?

**Comment by hipsterjazzbo** [comment]
Good point, I've just fixed and tagged `v0.0.4`.
